#多数据源
spring:
  datasource:
    hikari:
      db1:
        jdbc-url: jdbc:mysql://192.168.1.182:3306/erp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: dev*123
        driver-class-name: com.mysql.jdbc.Driver
      db2:
          jdbc-url: jdbc:mysql://192.168.1.182:3305/erp2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: dev*123
          driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml